name = input("Enter the name: ")
clas = input("Enter the Class: ")
realm = input("Enter the Home Realm: ")
ablty = input("Enter the special ability: ")
wpn = input("Enter the chosen weapon: ")
print('========================================')
print('     -- CHARACTER CREATION COMPLETE --')
print('========================================\n')
print('Name:     ', name)
print('Class:    ', clas)
print('Realm:    ', realm)
print()
print('Title: ', name, 'the', clas, 'of', realm)
print()
print('----------------------------------------')
print('Weapon of Choice: ', wpn)
print('Special Ability:  ', ablty)
print('========================================')
